# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=300)),
                ('graph_num', models.IntegerField()),
                ('completed', models.BooleanField(default='false')),
            ],
        ),
        migrations.CreateModel(
            name='Actuin_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('file_name', models.CharField(max_length=300)),
                ('graph_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Galaxy_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('computed', models.BooleanField(default='false')),
            ],
        ),
        migrations.CreateModel(
            name='Graph_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('graph_num', models.IntegerField()),
            ],
        ),
    ]
