# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0002_action_log_actuin_info_galaxy_image_graph_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('point_1_x', models.IntegerField()),
                ('point_1_y', models.IntegerField()),
                ('point_2_x', models.IntegerField()),
                ('point_2_y', models.IntegerField()),
                ('file_name', models.CharField(max_length=300)),
                ('graph_num', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Actuin_Info',
        ),
        migrations.RemoveField(
            model_name='graph_info',
            name='graph_num',
        ),
        migrations.AddField(
            model_name='graph_info',
            name='graph_count',
            field=models.IntegerField(default=0),
        ),
    ]
