# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0005_auto_20160111_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_info',
            name='y_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph_info',
            name='y_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
