# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0006_auto_20160111_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_info',
            name='graph_num',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
