# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0007_graph_info_graph_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph_info',
            old_name='graph_num',
            new_name='graph_name',
        ),
    ]
