# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0009_auto_20160111_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_info',
            name='y_max',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='graph_info',
            name='y_min',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
