# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0010_auto_20160112_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_info',
            name='x_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph_info',
            name='x_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
